In [6]:
from itertools import combinations
from scipy.spatial import distance

import numpy as np
import re

In [8]:
origin_path = 'corpus/distance_table_100mfw_0c.txt'
posgram_path = 'stanza_allposgram/distance_table_100mfw_0c.txt'

In [45]:
def read_dist_table(path):
    with open('D:/Nika/3/lingstylo/' + path) as f:
        table = f.read()
    #table = re.sub(' ', ',', table)
    matrix = []
    for vect in table.split('\n')[1:-1]:
        new_vect = []
        for num in vect.split(' ')[1:]:
            new_vect.append(float(num))
        matrix.append(new_vect)
    return np.array(matrix)

In [35]:
with open('D:/Nika/3/lingstylo/corpus/distance_table_100mfw_0c.txt') as f:
    table = f.read()
#table = re.sub(' ', ',', table)
#print(table[:20])
matrix = []
table.split('\n')[-1]

"Dostoevsky_BednieLy


''

In [ ]:
list_of_phrase_vects_dists = []
list_of_noun_vects_dists = []

for i in combinations(all_vectors_list, 2):
    list_of_phrase_vects_dists.append(distance.cosine(i[0], i[1]))

for i in combinations(noun_vectors_list, 2):
    list_of_noun_vects_dists.append(distance.cosine(i[0], i[1]))

In [37]:
read_dist_table(origin_path)
#len(read_dist_table(origin_path)[0])

[[0.0,
  1.04947937401832,
  1.01206723348761,
  1.0257333163446,
  1.19357666166999,
  1.53822503917884,
  1.35121109934112,
  1.35755928983943,
  1.13833813592793,
  1.24162028878188,
  1.46571489647426,
  1.82804701460071,
  1.50072043804266,
  1.61400277884774,
  1.58226510257299,
  1.69404447297665,
  1.52667149725402,
  1.47607365064037,
  1.23603572380425,
  1.24558238403066],
 [1.04947937401832,
  0.0,
  0.538348711681966,
  0.790722057817529,
  0.904093057934204,
  1.20467482684757,
  1.06751632916181,
  1.0752436224841,
  0.922643619432588,
  1.01122039205665,
  1.04435699060317,
  1.36337721290464,
  1.28476075182699,
  1.15629188074441,
  1.2426466649885,
  1.21311271544049,
  1.02550933295282,
  1.0210777603149,
  0.797034699956173,
  0.822281886502537],
 [1.01206723348761,
  0.538348711681966,
  0.0,
  0.641678646393183,
  0.92744590499034,
  1.2729982723735,
  1.00341433239599,
  1.04858473152261,
  0.880804939260868,
  1.07653249678973,
  1.14733354369566,
  1.485344214

In [46]:
np.corrcoef(read_dist_table(origin_path), read_dist_table(posgram_path))

array([[ 1.        ,  0.43107784,  0.51116745, ..., -0.2453629 ,
         0.08704586,  0.04475055],
       [ 0.43107784,  1.        ,  0.83312605, ...,  0.24188058,
         0.5229625 ,  0.4729091 ],
       [ 0.51116745,  0.83312605,  1.        , ...,  0.21164193,
         0.52669312,  0.51494218],
       ...,
       [-0.2453629 ,  0.24188058,  0.21164193, ...,  1.        ,
         0.69614289,  0.71089739],
       [ 0.08704586,  0.5229625 ,  0.52669312, ...,  0.69614289,
         1.        ,  0.87398525],
       [ 0.04475055,  0.4729091 ,  0.51494218, ...,  0.71089739,
         0.87398525,  1.        ]])

In [47]:
np.linalg.norm(read_dist_table(origin_path) - read_dist_table(posgram_path))

2.9189973494536874

In [48]:
np.linalg.norm(read_dist_table(posgram_path) - read_dist_table(origin_path))

2.9189973494536874

In [49]:
read_dist_table(origin_path) - read_dist_table(posgram_path)

array([[ 0.        , -0.03293645,  0.05075049, -0.0236856 , -0.08490516,
        -0.2379213 ,  0.02492263,  0.03363007,  0.04175483, -0.03723994,
        -0.19483553, -0.23486538, -0.09751846,  0.13682512,  0.35437391,
         0.04115114,  0.05988181, -0.14894203, -0.03399575, -0.0484575 ],
       [-0.03293645,  0.        ,  0.03606082, -0.0185312 ,  0.06892649,
        -0.03424122,  0.20638334,  0.2326134 ,  0.09114226,  0.18732707,
        -0.09427573,  0.05590002,  0.2649761 ,  0.20286097,  0.05495014,
         0.23312326,  0.08185001,  0.07677129,  0.10113414,  0.12408933],
       [ 0.05075049,  0.03606082,  0.        ,  0.02574116, -0.01749586,
        -0.06113729,  0.27681325,  0.36574773,  0.23273855,  0.20942264,
        -0.15439053,  0.06666832,  0.29977662,  0.2721751 ,  0.26099435,
         0.19075891,  0.11256921,  0.12338355,  0.1648022 ,  0.20116493],
       [-0.0236856 , -0.0185312 ,  0.02574116,  0.        , -0.12618567,
        -0.21127459,  0.05426485,  0.12656969,  

In [43]:
from scipy.spatial import distance
distance.cdist(np.array(read_dist_table(origin_path)), np.array(read_dist_table(posgram_path)), metric='euclidean')

array([[0.59230106, 2.54892851, 2.56111011, 1.97567938, 2.49420382,
        2.65355947, 2.75502832, 2.70338639, 2.4187812 , 2.66923892,
        2.67094405, 3.10090664, 2.65415864, 2.71765451, 2.11979619,
        2.89544647, 2.88673337, 2.77789254, 2.76483433, 2.88016839],
       [2.34221113, 0.6063963 , 1.12104189, 1.54634508, 1.60063687,
        2.55350869, 1.64252617, 1.61026228, 1.56618154, 1.53420621,
        2.17140379, 2.86795583, 2.01192756, 1.79636816, 2.22769589,
        2.05733137, 1.74869459, 1.71667005, 1.37411254, 1.47798049],
       [2.18877292, 1.05379621, 0.84217597, 1.28621903, 1.76943827,
        2.65819274, 1.61590968, 1.5560736 , 1.43347717, 1.69585817,
        2.35651332, 3.00577878, 2.15852333, 1.86673019, 2.16309565,
        2.23465421, 1.91192937, 1.82870129, 1.46480967, 1.52506554],
       [2.03176151, 1.44885538, 1.303709  , 0.56422343, 2.07487533,
        2.79797107, 1.78395838, 1.63551816, 1.51648443, 1.83132851,
        2.45062194, 3.0136195 , 2.14256779, 1